import { AppUser } from "../types/userProfile";

export const appUsers: AppUser[] = [
  {
    id: 1,
    firstname: "Emma",
    lastname: "Johnson",
    email: "emma.johnson@example.com",
    last_login: "2024-11-20 14:23:45",
    account_created: "2023-01-15 10:11:22",
    last_updated: "2024-10-18 09:33:27",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
    prefecture: "tokyo",
    city_ward: "shibuya",
    street_address: "1-2-3 Sakura Heights",
    postal_code: "150-0001",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 1,
    owner_id: null,
    sitter_profile: {
      id: 1,
      aggregate_sitter_rating: 4.8,
      profile_bio: "Animal lover with 5 years of experience caring for pets.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",

      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: false,
      rabbits_ok: false,
    },
  },
  {
    id: 2,
    firstname: "Kenji",
    lastname: "Tanaka",
    email: "kenji.tanaka@example.jp",
    last_login: "2024-11-21 08:15:10",
    account_created: "2022-09-10 16:42:18",
    last_updated: "2024-09-15 11:11:11",
    profile_picture_src:
      "https://live.staticflickr.com/62/207176169_60738224b6_c.jpg",
    prefecture: "Osaka",
    city_ward: "Kita",
    street_address: "2-5-10 Naniwa Building",
    postal_code: "530-0001",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: null,
    owner_id: 2,
    sitter_profile: {
      id: 2,
      aggregate_sitter_rating: 4.3,
      profile_bio: "Experienced sitter specialising in small animals.",
      bio_picture_src_list:
        "https://live.staticflickr.com/62/207176169_60738224b6_c.jpg",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: false,
      dogs_ok: false,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: true,
    },
  },
  {
    id: 3,
    firstname: "Sophia",
    lastname: "Williams",
    email: "sophia.williams@example.com",
    last_login: "2024-11-19 17:50:05",
    account_created: "2023-03-25 14:00:00",
    last_updated: "2024-11-01 10:20:15",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmkRHRtkrvooPGjWA-GsLDUOyy8hV7F8fRQA&s",
    prefecture: "Kyoto",
    city_ward: "Nakagyo",
    street_address: "6-4-3 Maple Court",
    postal_code: "604-0000",
    account_language: "en",
    english_ok: true,
    japanese_ok: false,
    sitter_id: 3,
    owner_id: null,
    sitter_profile: {
      id: 3,
      aggregate_sitter_rating: 5.0,
      profile_bio: "Professional pet sitter available for in-home care.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmkRHRtkrvooPGjWA-GsLDUOyy8hV7F8fRQA&s",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: false,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: true,
    },
  },
  {
    id: 4,
    firstname: "Haruto",
    lastname: "Suzuki",
    email: "haruto.suzuki@example.jp",
    last_login: "2024-11-18 20:05:30",
    account_created: "2021-06-10 13:45:00",
    last_updated: "2024-08-25 12:10:50",
    profile_picture_src:
      "https://d3544la1u8djza.cloudfront.net/APHI/Blog/2023/October/DogSitter-Hero.jpg",
    prefecture: "Kanagawa",
    city_ward: "Yokohama",
    street_address: "8-12-5 Horizon Tower",
    postal_code: "220-0001",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: null,
    owner_id: 4,
    sitter_profile: {
      id: 4,
      aggregate_sitter_rating: 3.9,
      profile_bio: "Part-time sitter with a passion for dogs.",
      bio_picture_src_list:
        "https://d3544la1u8djza.cloudfront.net/APHI/Blog/2023/October/DogSitter-Hero.jpg",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: false,
      fish_ok: false,
      birds_ok: false,
      rabbits_ok: false,
    },
  },
  {
    id: 5,
    firstname: "Liam",
    lastname: "Brown",
    email: "liam.brown@example.com",
    last_login: "2024-11-17 11:11:11",
    account_created: "2020-05-01 15:30:00",
    last_updated: "2024-06-20 14:20:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
    prefecture: "Fukuoka",
    city_ward: "Hakata",
    street_address: "5-7-9 River Front",
    postal_code: "812-0011",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 5,
    owner_id: null,
    sitter_profile: {
      id: 5,
      aggregate_sitter_rating: 4.6,
      profile_bio: "I love taking care of all kinds of pets.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: true,
    },
  },

  {
    id: 6,
    firstname: "Hana",
    lastname: "Yamamoto",
    email: "hana.yamamoto@example.jp",
    last_login: "2024-11-20 09:22:12",
    account_created: "2022-12-01 08:45:30",
    last_updated: "2024-10-10 14:25:50",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW4r9cqwOBK4ObEJqQSj3BV2JYkwyZJCQhOw&s",
    prefecture: "Hokkaido",
    city_ward: "Sapporo",
    street_address: "2-1-6 White Pine Lane",
    postal_code: "060-0001",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: null,
    owner_id: 6,
    sitter_profile: {
      id: 6,
      aggregate_sitter_rating: 4.0,
      profile_bio: "Bird specialist with a calm and caring approach.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW4r9cqwOBK4ObEJqQSj3BV2JYkwyZJCQhOw&s",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: false,
      cats_ok: false,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
  {
    id: 7,
    firstname: "Ethan",
    lastname: "Smith",
    email: "ethan.smith@example.com",
    last_login: "2024-11-19 16:00:00",
    account_created: "2023-08-15 11:30:45",
    last_updated: "2024-09-25 10:00:00",
    profile_picture_src:
      "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
    prefecture: "Nagano",
    city_ward: "Matsumoto",
    street_address: "10-3-15 Alpine Road",
    postal_code: "390-0811",
    account_language: "en",
    english_ok: true,
    japanese_ok: false,
    sitter_id: 7,
    owner_id: null,
    sitter_profile: {
      id: 7,
      aggregate_sitter_rating: 3.5,
      profile_bio: "Friendly and flexible sitter for all types of pets.",
      bio_picture_src_list:
        "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: true,
    },
  },
  {
    id: 8,
    firstname: "Aiko",
    lastname: "Fujimoto",
    email: "aiko.fujimoto@example.jp",
    last_login: "2024-11-21 12:45:10",
    account_created: "2021-02-14 09:10:30",
    last_updated: "2024-11-01 17:15:20",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOK4fsobYKQ_WxzaenKWLlADdJYULH0MvwibpmliXdcPHwZ3P_UusFp9VVhvN9iOOILus&usqp=CAU",
    prefecture: "Chiba",
    city_ward: "Narita",
    street_address: "7-5-11 Sakura Plaza",
    postal_code: "286-0031",
    account_language: "ja",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 8,
    owner_id: null,
    sitter_profile: {
      id: 8,
      aggregate_sitter_rating: 4.7,
      profile_bio: "Full-time pet sitter who loves cats and dogs.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOK4fsobYKQ_WxzaenKWLlADdJYULH0MvwibpmliXdcPHwZ3P_UusFp9VVhvN9iOOILus&usqp=CAU",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: false,
      birds_ok: false,
      rabbits_ok: false,
    },
  },
  {
    id: 9,
    firstname: "Oliver",
    lastname: "Taylor",
    email: "oliver.taylor@example.com",
    last_login: "2024-11-18 20:10:55",
    account_created: "2022-07-01 15:25:30",
    last_updated: "2024-10-05 09:00:00",
    profile_picture_src:
      "https://2pawsupinc.com/wp-content/uploads/2018/05/why-hire-a-professional-pet-sitter.jpg",
    prefecture: "Okinawa",
    city_ward: "Naha",
    street_address: "3-12-9 Ocean Breeze Street",
    postal_code: "900-0015",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: null,
    owner_id: 9,
    sitter_profile: {
      id: 9,
      aggregate_sitter_rating: 4.2,
      profile_bio: "Weekend sitter for small and exotic animals.",
      bio_picture_src_list:
        "https://2pawsupinc.com/wp-content/uploads/2018/05/why-hire-a-professional-pet-sitter.jpg",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: false,
      cats_ok: false,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: true,
    },
  },
  {
    id: 10,
    firstname: "Sakura",
    lastname: "Matsui",
    email: "sakura.matsui@example.jp",
    last_login: "2024-11-22 08:30:20",
    account_created: "2020-11-25 17:45:50",
    last_updated: "2024-08-15 10:30:15",
    profile_picture_src:
      "https://www.rover.com/cf-image-cdn/remote/images/people/Nvz4RY0N/njqdymnrkm/original?width=450&height=450&quality=70&fit=cover",
    prefecture: "Hiroshima",
    city_ward: "Minami",
    street_address: "4-9-8 Peace Avenue",
    postal_code: "734-0000",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: 10,
    owner_id: null,
    sitter_profile: {
      id: 10,
      aggregate_sitter_rating: 4.9,
      profile_bio: "Experienced pet sitter with a love for rabbits and cats.",
      bio_picture_src_list:
        "https://www.rover.com/cf-image-cdn/remote/images/people/Nvz4RY0N/njqdymnrkm/original?width=450&height=450&quality=70&fit=cover",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: false,
      dogs_ok: false,
      cats_ok: true,
      fish_ok: false,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 11,
    firstname: "Hiroshi",
    lastname: "Kobayashi",
    email: "hiroshi.kobayashi@example.jp",
    last_login: "2024-11-15 09:30:00",
    account_created: "2022-10-20 14:22:30",
    last_updated: "2024-10-01 11:30:45",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
    prefecture: "Nagano",
    city_ward: "Matsumoto",
    street_address: "10-5-1 Cherry Blossom Street",
    postal_code: "390-0815",
    account_language: "ja",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 11,
    owner_id: null,
    sitter_profile: {
      id: 11,
      aggregate_sitter_rating: 4.5,
      profile_bio: "Reliable and experienced pet sitter for all occasions.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
  {
    id: 12,
    firstname: "Aya",
    lastname: "Nakagawa",
    email: "aya.nakagawa@example.jp",
    last_login: "2024-11-14 10:45:00",
    account_created: "2021-06-30 09:15:25",
    last_updated: "2024-09-20 15:45:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW4r9cqwOBK4ObEJqQSj3BV2JYkwyZJCQhOw&s",
    prefecture: "Tokyo",
    city_ward: "Shinjuku",
    street_address: "5-8-3 Sky Tower",
    postal_code: "160-0022",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: 12,
    owner_id: null,
    sitter_profile: {
      id: 12,
      aggregate_sitter_rating: 4.2,
      profile_bio: "Loving pet sitter who specialises in small animals.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW4r9cqwOBK4ObEJqQSj3BV2JYkwyZJCQhOw&s",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: false,
      cats_ok: true,
      fish_ok: true,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 13,
    firstname: "James",
    lastname: "White",
    email: "james.white@example.com",
    last_login: "2024-11-13 14:00:00",
    account_created: "2023-05-01 10:30:00",
    last_updated: "2024-10-15 12:45:00",
    profile_picture_src:
      "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
    prefecture: "Osaka",
    city_ward: "Naniwa",
    street_address: "7-2-10 Riverfront",
    postal_code: "550-0015",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 13,
    owner_id: null,
    sitter_profile: {
      id: 13,
      aggregate_sitter_rating: 4.8,
      profile_bio: "Dedicated pet sitter with a passion for dogs and cats.",
      bio_picture_src_list:
        "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
  {
    id: 14,
    firstname: "Mika",
    lastname: "Tanaka",
    email: "mika.tanaka@example.jp",
    last_login: "2024-11-12 18:30:00",
    account_created: "2020-08-12 12:00:00",
    last_updated: "2024-10-10 10:30:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
    prefecture: "Chiba",
    city_ward: "Narita",
    street_address: "8-4-1 Sakura Gardens",
    postal_code: "286-0032",
    account_language: "ja",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 14,
    owner_id: null,
    sitter_profile: {
      id: 14,
      aggregate_sitter_rating: 4.9,
      profile_bio: "Experienced sitter with a love for all pets.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: true,
    },
  },
  {
    id: 15,
    firstname: "Alex",
    lastname: "Green",
    email: "alex.green@example.com",
    last_login: "2024-11-11 16:45:00",
    account_created: "2023-07-22 14:45:00",
    last_updated: "2024-09-18 11:00:00",
    profile_picture_src:
      "https://www.rover.com/cf-image-cdn/remote/images/people/Nvz4RY0N/njqdymnrkm/original?width=450&height=450&quality=70&fit=cover",
    prefecture: "Hokkaido",
    city_ward: "Sapporo",
    street_address: "2-1-6 Pine Forest Lane",
    postal_code: "060-0002",
    account_language: "en",
    english_ok: true,
    japanese_ok: false,
    sitter_id: 15,
    owner_id: null,
    sitter_profile: {
      id: 15,
      aggregate_sitter_rating: 4.7,
      profile_bio: "Professional pet sitter available for flexible hours.",
      bio_picture_src_list:
        "https://www.rover.com/cf-image-cdn/remote/images/people/Nvz4RY0N/njqdymnrkm/original?width=450&height=450&quality=70&fit=cover",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: false,
      rabbits_ok: false,
    },
  },
  {
    id: 16,
    firstname: "Naoko",
    lastname: "Yamada",
    email: "naoko.yamada@example.jp",
    last_login: "2024-11-10 14:15:00",
    account_created: "2021-04-15 09:00:00",
    last_updated: "2024-10-08 15:30:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
    prefecture: "Kanagawa",
    city_ward: "Yokohama",
    street_address: "3-5-9 Portside Avenue",
    postal_code: "231-0023",
    account_language: "ja",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 16,
    owner_id: null,
    sitter_profile: {
      id: 16,
      aggregate_sitter_rating: 4.6,
      profile_bio: "Friendly sitter with extensive experience with dogs.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: false,
      fish_ok: true,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 17,
    firstname: "Takeshi",
    lastname: "Shimizu",
    email: "takeshi.shimizu@example.jp",
    last_login: "2024-11-09 13:50:00",
    account_created: "2020-12-25 10:45:00",
    last_updated: "2024-09-05 09:15:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW4r9cqwOBK4ObEJqQSj3BV2JYkwyZJCQhOw&s",
    prefecture: "Aichi",
    city_ward: "Nagoya",
    street_address: "4-8-2 Green Hill",
    postal_code: "460-0001",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: 17,
    owner_id: null,
    sitter_profile: {
      id: 17,
      aggregate_sitter_rating: 4.3,
      profile_bio: "Energetic sitter ready for long pet walks.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW4r9cqwOBK4ObEJqQSj3BV2JYkwyZJCQhOw&s",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: false,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
  {
    id: 18,
    firstname: "Sophie",
    lastname: "Brown",
    email: "sophie.brown@example.com",
    last_login: "2024-11-08 08:20:00",
    account_created: "2023-02-14 11:00:00",
    last_updated: "2024-09-25 14:00:00",
    profile_picture_src:
      "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
    prefecture: "Fukuoka",
    city_ward: "Hakata",
    street_address: "6-9-12 Sunset Boulevard",
    postal_code: "812-0018",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 18,
    owner_id: null,
    sitter_profile: {
      id: 18,
      aggregate_sitter_rating: 4.9,
      profile_bio: "Caring sitter with special training in pet first aid.",
      bio_picture_src_list:
        "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: false,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 19,
    firstname: "Koji",
    lastname: "Matsuda",
    email: "koji.matsuda@example.jp",
    last_login: "2024-11-07 19:15:00",
    account_created: "2022-01-01 09:30:00",
    last_updated: "2024-08-12 16:00:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
    prefecture: "Kyoto",
    city_ward: "Sakyo",
    street_address: "1-3-5 Riverwalk Lane",
    postal_code: "606-8107",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: 19,
    owner_id: null,
    sitter_profile: {
      id: 19,
      aggregate_sitter_rating: 4.1,
      profile_bio:
        "Nature lover who enjoys caring for pets in calm environments.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: false,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
  {
    id: 20,
    firstname: "Emily",
    lastname: "Clark",
    email: "emily.clark@example.com",
    last_login: "2024-11-06 15:50:00",
    account_created: "2023-10-03 17:15:00",
    last_updated: "2024-09-10 13:30:00",
    profile_picture_src:
      "https://www.rover.com/cf-image-cdn/remote/images/people/Nvz4RY0N/njqdymnrkm/original?width=450&height=450&quality=70&fit=cover",
    prefecture: "Okinawa",
    city_ward: "Naha",
    street_address: "9-4-7 Ocean Breeze",
    postal_code: "900-0034",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 20,
    owner_id: null,
    sitter_profile: {
      id: 20,
      aggregate_sitter_rating: 4.4,
      profile_bio: "Passionate about providing the best care for pets.",
      bio_picture_src_list:
        "https://www.rover.com/cf-image-cdn/remote/images/people/Nvz4RY0N/njqdymnrkm/original?width=450&height=450&quality=70&fit=cover",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: false,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 21,
    firstname: "Haruto",
    lastname: "Takahashi",
    email: "haruto.takahashi@example.jp",
    last_login: "2024-11-05 12:45:00",
    account_created: "2021-06-18 08:00:00",
    last_updated: "2024-10-01 11:30:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
    prefecture: "Osaka",
    city_ward: "Kita",
    street_address: "7-2-5 Sakura Street",
    postal_code: "530-0001",
    account_language: "ja",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 21,
    owner_id: null,
    sitter_profile: {
      id: 21,
      aggregate_sitter_rating: 4.5,
      profile_bio: "Experienced pet sitter with a focus on elderly pets.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: false,
      fish_ok: true,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 22,
    firstname: "Akari",
    lastname: "Yoshida",
    email: "akari.yoshida@example.jp",
    last_login: "2024-11-04 10:20:00",
    account_created: "2022-05-03 12:30:00",
    last_updated: "2024-08-18 14:45:00",
    profile_picture_src:
      "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
    prefecture: "Hyogo",
    city_ward: "Kobe",
    street_address: "3-6-1 Mountain View",
    postal_code: "651-0012",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: 22,
    owner_id: null,
    sitter_profile: {
      id: 22,
      aggregate_sitter_rating: 4.2,
      profile_bio: "Friendly and reliable sitter for cats and rabbits.",
      bio_picture_src_list:
        "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: false,
      cats_ok: true,
      fish_ok: false,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 23,
    firstname: "Michael",
    lastname: "Smith",
    email: "michael.smith@example.com",
    last_login: "2024-11-03 09:10:00",
    account_created: "2023-01-28 15:20:00",
    last_updated: "2024-07-10 17:00:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
    prefecture: "Tokyo",
    city_ward: "Shibuya",
    street_address: "5-3-2 Maple Avenue",
    postal_code: "150-0002",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 23,
    owner_id: null,
    sitter_profile: {
      id: 23,
      aggregate_sitter_rating: 4.8,
      profile_bio: "Dedicated sitter with a passion for exotic pets.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
  {
    id: 24,
    firstname: "Riko",
    lastname: "Tanaka",
    email: "riko.tanaka@example.jp",
    last_login: "2024-11-02 14:25:00",
    account_created: "2020-09-10 08:40:00",
    last_updated: "2024-06-01 11:30:00",
    profile_picture_src:
      "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
    prefecture: "Hokkaido",
    city_ward: "Sapporo",
    street_address: "8-1-2 Snowflake Lane",
    postal_code: "060-0042",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: 24,
    owner_id: null,
    sitter_profile: {
      id: 24,
      aggregate_sitter_rating: 4.0,
      profile_bio:
        "Nature enthusiast who loves caring for pets in quiet settings.",
      bio_picture_src_list:
        "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: false,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 25,
    firstname: "Daniel",
    lastname: "Johnson",
    email: "daniel.johnson@example.com",
    last_login: "2024-11-01 18:30:00",
    account_created: "2023-04-05 14:10:00",
    last_updated: "2024-05-10 10:00:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
    prefecture: "Miyagi",
    city_ward: "Sendai",
    street_address: "2-4-3 Sunrise Street",
    postal_code: "980-0811",
    account_language: "en",
    english_ok: true,
    japanese_ok: false,
    sitter_id: 25,
    owner_id: null,
    sitter_profile: {
      id: 25,
      aggregate_sitter_rating: 4.7,
      profile_bio: "Trustworthy sitter who excels in training puppies.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
      sitter_house_ok: true,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: true,
    },
  },
  {
    id: 26,
    firstname: "Hana",
    lastname: "Fujimoto",
    email: "hana.fujimoto@example.jp",
    last_login: "2024-11-01 20:15:00",
    account_created: "2022-11-12 09:20:00",
    last_updated: "2024-09-21 13:45:00",
    profile_picture_src:
      "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
    prefecture: "Kyoto",
    city_ward: "Fushimi",
    street_address: "6-7-8 Bamboo Grove",
    postal_code: "612-0801",
    account_language: "ja",
    english_ok: false,
    japanese_ok: true,
    sitter_id: 26,
    owner_id: null,
    sitter_profile: {
      id: 26,
      aggregate_sitter_rating: 4.1,
      profile_bio: "Animal lover with experience in bird care.",
      bio_picture_src_list:
        "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: false,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
  {
    id: 27,
    firstname: "Kaito",
    lastname: "Matsuda",
    email: "kaito.matsuda@example.jp",
    last_login: "2024-11-01 19:00:00",
    account_created: "2021-03-15 15:10:00",
    last_updated: "2024-08-05 12:30:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
    prefecture: "Nagano",
    city_ward: "Matsumoto",
    street_address: "4-5-1 Castle Hill",
    postal_code: "390-0812",
    account_language: "ja",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 27,
    owner_id: null,
    sitter_profile: {
      id: 27,
      aggregate_sitter_rating: 4.6,
      profile_bio: "Experienced with large dog breeds and active pets.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7IWtIwnOwCcE2uGK82fdn303zm2foXLhxoA&s",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: false,
      fish_ok: true,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 28,
    firstname: "Liam",
    lastname: "Walker",
    email: "liam.walker@example.com",
    last_login: "2024-10-30 16:50:00",
    account_created: "2023-07-19 18:30:00",
    last_updated: "2024-06-18 09:15:00",
    profile_picture_src:
      "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
    prefecture: "Fukuoka",
    city_ward: "Hakata",
    street_address: "3-6-7 River Street",
    postal_code: "812-0013",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 28,
    owner_id: null,
    sitter_profile: {
      id: 28,
      aggregate_sitter_rating: 4.9,
      profile_bio: "Patient sitter who excels with anxious pets.",
      bio_picture_src_list:
        "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: false,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
  {
    id: 29,
    firstname: "Yui",
    lastname: "Nakamura",
    email: "yui.nakamura@example.jp",
    last_login: "2024-10-28 11:25:00",
    account_created: "2022-08-21 10:50:00",
    last_updated: "2024-07-01 15:00:00",
    profile_picture_src:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
    prefecture: "Shizuoka",
    city_ward: "Hamamatsu",
    street_address: "5-8-3 Seaside Boulevard",
    postal_code: "430-0929",
    account_language: "ja",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 29,
    owner_id: null,
    sitter_profile: {
      id: 29,
      aggregate_sitter_rating: 4.3,
      profile_bio: "Reliable sitter who loves outdoor walks with pets.",
      bio_picture_src_list:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7fEaFQ7CC3TK-PdJ6d0z5N_wTc1BQ-BLGVw&s",
      sitter_house_ok: true,
      owner_house_ok: false,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: true,
      fish_ok: false,
      birds_ok: false,
      rabbits_ok: true,
    },
  },
  {
    id: 30,
    firstname: "Oliver",
    lastname: "Brown",
    email: "oliver.brown@example.com",
    last_login: "2024-10-27 09:40:00",
    account_created: "2023-05-25 13:00:00",
    last_updated: "2024-05-12 16:20:00",
    profile_picture_src:
      "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
    prefecture: "Kanagawa",
    city_ward: "Yokohama",
    street_address: "7-9-2 Bay Area",
    postal_code: "220-0011",
    account_language: "en",
    english_ok: true,
    japanese_ok: true,
    sitter_id: 30,
    owner_id: null,
    sitter_profile: {
      id: 30,
      aggregate_sitter_rating: 4.7,
      profile_bio: "Energetic sitter who specialises in playful dogs.",
      bio_picture_src_list:
        "https://cdn.sentidoanimal.es/wp-content/uploads/2024/05/cabecera_Dogsitter_pk.jpg",
      sitter_house_ok: false,
      owner_house_ok: true,
      visit_ok: true,
      dogs_ok: true,
      cats_ok: false,
      fish_ok: true,
      birds_ok: true,
      rabbits_ok: false,
    },
  },
];
